/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.service;

import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioPageDTO;
import java.util.List;
import javax.ejb.Stateless;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import static javax.ws.rs.HttpMethod.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.UriInfo;

@Path("/Convenio")
@Stateless
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class ConvenioService extends _ConvenioService {
    
    
    //aca ponemos tal cual los parametros del page y maxrecord para pedir el parametro de la 
    //interfaz es necesario poner @QueryParam com oen este caso queria el paisID ps asi lo hice
    //una vez obtenidos los parametros llamamos el metodo que creamos anteriormente :D en este
    //caso filtrarColombia .  ahora finalmente pasamos al coveniDelegte que queda en el .web  .
    //a cada metodo se le asigna un id unico en este paso es pais y lo escribimos como @path("pais")
    //recordar el @pais para lo que escribo en el delegate
    
    @Context
      UriInfo uriInfo;
    
    @GET
	@Path("pais")
	public ConvenioPageDTO  filrarPais (@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords,@QueryParam("paisId") String paisID,@QueryParam("name") String nombre){
            if(!paisID.equals("")){
		return convenioLogicService.filtrarColombia(page,maxRecords,paisID);
        }
            
         
            
            return  convenioLogicService.filtrarColombia(page,maxRecords,"0");
          
        }
        
        
        
         @GET
	@Path("nombre")
	public ConvenioPageDTO  filrarNombre (@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords,@QueryParam("paisId") String paisID,@QueryParam("name") String nombre){
            
		return convenioLogicService.filtrarNombre(page, maxRecords, nombre);
	
            
         
            
           
          
        }
        
        
        
          @GET
	@Path("departamento")
	public ConvenioPageDTO  filrarDepartamento (@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords,@QueryParam("paisId") String paisID,@QueryParam("departamentouniandesId") String departamento){
            if(!departamento.equals("")){
		return convenioLogicService.filtrarDepartamento(page,maxRecords,departamento);
	}
            
         
            
            return  convenioLogicService.filtrarDepartamento(page,maxRecords,"0");
          
        }
        
        
          @GET
	@Path("facultad")
	public ConvenioPageDTO  filrarfacultad (@QueryParam("page") Integer page, @QueryParam("maxRecords") Integer maxRecords,@QueryParam("paisId") String paisID,@QueryParam("facultaduniandesId") String facultad){
            if(!facultad.equals("")){
		return convenioLogicService.filtrarFacultad(page,maxRecords,facultad);
	}
            
         
            
            return  convenioLogicService.filtrarFacultad(page,maxRecords,"0");
          
        }

}