/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.RoyalSystem.intercambio.persistence;


import co.edu.uniandes.csw.RoyalSystem.intercambio.logic.dto.IntercambioPageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.api.IIntercambioPersistence;
import co.edu.uniandes.csw.RoyalSystem.intercambio.persistence.converter.IntercambioConverter;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class IntercambioPersistence extends _IntercambioPersistence  implements IIntercambioPersistence {

    
    
    public IntercambioPageDTO getFiltrarEstado(Integer page , Integer maxRecords,String estadoId) {
        
         System.out.println("entro a buscar");
          System.out.println("el estadoid es : "+estadoId);
         
         
         String nombre=estadoId;
        
		
        
                // la consulta que queremos realizar se hace tando el count como el select ya que uno cuenta para
                //poder paginar y el otro hace la consulta
                
                Query count = entityManager.createQuery("select count(u) FROM IntercambioEntity u WHERE u.estadoId="+nombre);
                
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("SELECT u FROM IntercambioEntity u WHERE u.estadoId="+nombre);
      
                //solo copiamos y pagamos esta parte para q pagine
                
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		IntercambioPageDTO response = new IntercambioPageDTO();
		response.setTotalRecords(regCount);
		
                response.setRecords(IntercambioConverter.entity2PersistenceDTOList(q.getResultList()));
		System.out.println("acabo  buscar");
                return response;
        
        
        
        
    }

    

   
}