/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.persistence.api;

import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioPageDTO;
import java.util.List;

public interface IConvenioPersistence extends _IConvenioPersistence {
   
    
    // creamos la interfaz del metodo que tendra toda la infromacion , tener en cuenta que tenemos q retornar
    //un loqueseaPageDTO para que se pueda mostrar paginado. el codigo de este metodo lo tenemos que hacer en
    //la clase q lo implemente que en este caso es ConvenioPersistence
    
    public ConvenioPageDTO filtrarCol(Integer page, Integer maxrecords,String paisID);

    public ConvenioPageDTO filtrarNombre(Integer page, Integer maxrecord, String nombre);

    public ConvenioPageDTO filtrarDepartamento(Integer page, Integer maxrecord, String departamento);

    public ConvenioPageDTO filtrarFacultad(Integer page, Integer maxrecord, String facultad);

   
}