/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/
define(['model/_estudianteModel'], function() {
    App.Model.EstudianteModel = App.Model._EstudianteModel.extend({

 		validate: function(attrs,options){
            var validationMessage = "";
            if(!attrs.name){
                validationMessage = "The name can't be empty.";
            }
            
             if(!attrs.creditosAprovados){
                validationMessage = "Tienes que ingresa el numero de creditos aprobado";
            }
            
             if(!attrs.codigo){
                validationMessage = "Tienes que ingresa el codigo";
            }
             if(!attrs.promedio){
                validationMessage = "Tienes que ingresa el promedio";
            }
            
             if( !parseInt(attrs.creditosAprovados)>0){
                validationMessage = "El numero de creditos debe ser mayor a 0";
            }
            
            if( parseInt(attrs.codigo)<1000000){
                validationMessage = "El codigo ingresado no es valido";
            }
            
            if( parseInt(attrs.promedio)<1.5 ){
                validationMessage = "El promedio debe estar entre 1.5 y 5";
            }
             if( parseInt(attrs.promedio)>5.0001){
                validationMessage = "El promedio debe estar entre 1.5 y 5";
            }
            if(!attrs.tipoId){
                validationMessage = "Tienes que seleccionar un tipo";
            }
            
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.EstudianteList = App.Model._EstudianteList.extend({
        model: App.Model.EstudianteModel
    });

    return  App.Model.EstudianteModel;

});