/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.api.IConvenioLogicService;
import co.edu.uniandes.csw.RoyalSystem.convenio.master.logic.api._IConvenioMasterLogicService;
import co.edu.uniandes.csw.RoyalSystem.convenio.master.logic.dto.ConvenioMasterDTO;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.api.IHomologacionLogicService;
import co.edu.uniandes.csw.RoyalSystem.homologacion.logic.dto.HomologacionDTO;
import javax.inject.Inject;


public abstract class _ConvenioMasterMockLogicService implements _IConvenioMasterLogicService {

    protected static ArrayList<ConvenioMasterDTO> convenioMasterDtosList = new ArrayList<ConvenioMasterDTO>() ;
    @Inject
    protected IHomologacionLogicService homologacionPersistance;
    @Inject
    protected IConvenioLogicService convenioPersistance;

    public ConvenioMasterDTO createMasterConvenio(ConvenioMasterDTO convenio) {

        convenioPersistance.createConvenio(convenio.getConvenioEntity());
        for (HomologacionDTO dto : convenio.getCreatehomologacion()) {
            homologacionPersistance.createHomologacion(dto);
        }
        convenioMasterDtosList.add(convenio);
        return convenio;
    }

    public ConvenioMasterDTO getMasterConvenio(Long id) {
        for (ConvenioMasterDTO convenioMasterDTO : convenioMasterDtosList) {
            if (convenioMasterDTO.getConvenioEntity().getId() == id) {
                return convenioMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterConvenio(Long id) {
        for (ConvenioMasterDTO convenioMasterDTO : convenioMasterDtosList) {
            if (convenioMasterDTO.getConvenioEntity().getId() == id) {

                for (HomologacionDTO dto : convenioMasterDTO.getCreatehomologacion()) {
                    homologacionPersistance.deleteHomologacion(dto.getId());
                }
                convenioPersistance.deleteConvenio(convenioMasterDTO.getId());
                convenioMasterDtosList.remove(convenioMasterDTO);
            }
        }

    }

    public void updateMasterConvenio(ConvenioMasterDTO convenio) {

        // update Homologacion
        if (convenio.getUpdatehomologacion() != null) {
            for (HomologacionDTO dto : convenio.getUpdatehomologacion()) {
                homologacionPersistance.updateHomologacion(dto);
            }
        }
        // persist new Homologacion
        if (convenio.getCreatehomologacion() != null) {
            for (HomologacionDTO dto : convenio.getCreatehomologacion()) {
                HomologacionDTO persistedHomologacionDTO = homologacionPersistance.createHomologacion(dto);
                dto = persistedHomologacionDTO;
            }
        }
        // delete Homologacion
        if (convenio.getDeletehomologacion() != null) {
            for (HomologacionDTO dto : convenio.getDeletehomologacion()) {

                homologacionPersistance.deleteHomologacion(dto.getId());
            }
        }
    }
}