/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/

package co.edu.uniandes.csw.RoyalSystem.convenio.persistence;

import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioDTO;
import co.edu.uniandes.csw.RoyalSystem.convenio.logic.dto.ConvenioPageDTO;
import javax.ejb.Stateless;
import javax.enterprise.inject.Default;

import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.api.IConvenioPersistence;
import co.edu.uniandes.csw.RoyalSystem.convenio.persistence.converter.ConvenioConverter;
import java.util.List;
import javax.ejb.LocalBean;
import javax.persistence.Query;

@Default
@Stateless 
@LocalBean
public class ConvenioPersistence extends _ConvenioPersistence  implements IConvenioPersistence {

    // toda la implementacion del codigo este aca, aca acabamos toda la parte de logica , 
    //ahora debemos modificar 
        //el toulbar para el llamado desde interfaz y empezaremos por el 
    
    public ConvenioPageDTO filtrarCol(Integer page , Integer maxRecords,String paisID) {
       
        
        //el id del pais que queremos filtrar 
        
        String nombre=paisID;
        
		
        
                // la consulta que queremos realizar se hace tando el count como el select ya que uno cuenta para
                //poder paginar y el otro hace la consulta
                
                Query count = entityManager.createQuery("select count(u) FROM ConvenioEntity u WHERE u.paisId="+nombre);
                
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("SELECT u FROM ConvenioEntity u WHERE u.paisId="+nombre);
      
                //solo copiamos y pagamos esta parte para q pagine
                
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ConvenioPageDTO response = new ConvenioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ConvenioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
        
        
    }

    



}