/* ========================================================================
 * Copyright 2014 RoyalSystem
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 RoyalSystem

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201410152247

*/
define(['component/_convenioComponent'], function() {
    App.Component.ConvenioComponent = App.Component._ConvenioComponent.extend({
       
       //modificamos el posInit para poner un nuevo boton en el toulbar en este
       //caso lo llamaremos excexsearhc y hacemos que llame al metodo que queramos del
       // cotroler que en este caso sera userSearch, ahora pasamos al controller
       
        postInit: function(){
            
            
             this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('print');
               
             
           
            this.toolbarComponent.addButton({
                  name: 'filtrarNombre',
                  displayName: 'Filtrar Por Nombre',
                 icon: 'glyphicon-search',
                 show: false
              },
             this.filtrarNombre,
             this); 
             
             
             this.toolbarComponent.addButton({
                  name: 'filtrarFacultad',
                  displayName: 'Filtrar Por Facultad',
                 icon: 'glyphicon-search',
                 show: false
              },
             this.filtrarFacultad,
             this);
             
             
             this.toolbarComponent.addButton({
                  name: 'filtrarDepartamento',
                  displayName: 'Filtrar Por Departamento',
                 icon: 'glyphicon-search',
                 show: false
              },
             this.filtrarDepartamento,
             this);
            
            
            
              this.toolbarComponent.addButton({
                  name: 'exec-search',
                  displayName: 'Filtrar Por Pais',
                 icon: 'glyphicon-search',
                 show: false
              },
             this.execSearch,
             this);
             
             
              this.toolbarComponent.addButton({
                  name: 'filtrar',
                  displayName: 'Filtrar',
                 icon: 'glyphicon-search',
                 show: true
              },
             this.filtrar,
             this);
             
             
             
             this.toolbarComponent.addButton({
                 name: 'cancel-search',
                 displayName: 'Cancel',
                 icon: 'glyphicon-remove-sign',
                 show: false
             },
             
                
             
             
             function(){
                
                 this.toolbarComponent.showButton('create');
                 this.toolbarComponent.showButton('refresh');
                 this.toolbarComponent.showButton('filtrar');
                 this.toolbarComponent.hideButton('print');
                this.toolbarComponent.hideButton('search');
                 this.toolbarComponent.hideButton('cancel-search');
                 this.toolbarComponent.hideButton('exec-search');
                     this.toolbarComponent.hideButton('filtrarNombre');
             this.toolbarComponent.hideButton('filtrarDepartamento');
             this.toolbarComponent.hideButton('filtrarFacultad')
                 this.toolbarComponent.render();
                 this.componentController.list(null, this.list, this);
             },
             this);
         },
         filtrar: function(){
             this.toolbarComponent.hideButton('create');
             this.toolbarComponent.hideButton('save');
             this.toolbarComponent.hideButton('cancel');
             this.toolbarComponent.hideButton('print');
             this.toolbarComponent.hideButton('refresh');
             this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('filtrar');
             this.toolbarComponent.showButton('exec-search');
             this.toolbarComponent.showButton('filtrarNombre');
             this.toolbarComponent.showButton('filtrarDepartamento');
             this.toolbarComponent.showButton('filtrarFacultad');
             this.toolbarComponent.showButton('cancel-search');
             this.toolbarComponent.render();
             this.componentController.create();
         },
         execSearch: function(){
             this.toolbarComponent.showButton('create');
             this.toolbarComponent.showButton('refresh');
              this.toolbarComponent.showButton('filtrar');
             this.toolbarComponent.hideButton('print');
           this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('cancel-search');
             this.toolbarComponent.hideButton('exec-search');
              this.toolbarComponent.hideButton('filtrarNombre');
             this.toolbarComponent.hideButton('filtrarDepartamento');
             this.toolbarComponent.hideButton('filtrarFacultad')
             this.toolbarComponent.render();
             this.componentController.userSearch(this.list,this);
         }
         
         
         
         ,
         filtrarNombre: function(){
             this.toolbarComponent.showButton('create');
             this.toolbarComponent.showButton('refresh');
              this.toolbarComponent.showButton('filtrar');
             this.toolbarComponent.hideButton('print');
           this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('cancel-search');
             this.toolbarComponent.hideButton('exec-search');
              this.toolbarComponent.hideButton('filtrarNombre');
             this.toolbarComponent.hideButton('filtrarDepartamento');
             this.toolbarComponent.hideButton('filtrarFacultad')
             this.toolbarComponent.render();
             this.componentController.filtrarNombre(this.list,this);
         }
         
         ,
         filtrarFacultad: function(){
             this.toolbarComponent.showButton('create');
             this.toolbarComponent.showButton('refresh');
              this.toolbarComponent.showButton('filtrar');
             this.toolbarComponent.hideButton('print');
           this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('cancel-search');
             this.toolbarComponent.hideButton('exec-search');
              this.toolbarComponent.hideButton('filtrarNombre');
             this.toolbarComponent.hideButton('filtrarDepartamento');
             this.toolbarComponent.hideButton('filtrarFacultad')
             this.toolbarComponent.render();
             this.componentController.filtrarFacultad(this.list,this);
         }
         
         ,
         filtrarDepartamento: function(){
             this.toolbarComponent.showButton('create');
             this.toolbarComponent.showButton('refresh');
              this.toolbarComponent.showButton('filtrar');
             this.toolbarComponent.hideButton('print');
           this.toolbarComponent.hideButton('search');
             this.toolbarComponent.hideButton('cancel-search');
             this.toolbarComponent.hideButton('exec-search');
              this.toolbarComponent.hideButton('filtrarNombre');
             this.toolbarComponent.hideButton('filtrarDepartamento');
             this.toolbarComponent.hideButton('filtrarFacultad')
             this.toolbarComponent.render();
             this.componentController.filtrarDepartamento(this.list,this);
         }
         
         
         
        
     });
       
       
   
    return App.Component.ConvenioComponent;
});